/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.azure.storage;

import com.microsoft.rest.v2.RestClient;
import com.microsoft.rest.v2.ServiceClient;

/**
 * The interface for StorageClient class.
 */
public interface StorageClient {
    /**
     * Gets the REST client.
     *
     * @return the {@link RestClient} object.
    */
    ServiceClient restClient();

    /**
     * Gets the User-Agent header for the client.
     *
     * @return the user agent string.
     */
    String userAgent();

    /**
     * Gets The Azure storage account to use..
     *
     * @return the accountName value.
     */
    String accountName();

    /**
     * Sets The Azure storage account to use..
     *
     * @param accountName the accountName value.
     * @return the service client itself
     */
    StorageClient withAccountName(String accountName);

    /**
     * Gets Specifies the version of the operation to use for this request..
     *
     * @return the version value.
     */
    String version();

    /**
     * Sets Specifies the version of the operation to use for this request..
     *
     * @param version the version value.
     * @return the service client itself
     */
    StorageClient withVersion(String version);

    /**
     * Gets Provides a client-generated, opaque value with a 1 KB character limit that is recorded in the analytics logs when storage analytics logging is enabled..
     *
     * @return the requestId value.
     */
    String requestId();

    /**
     * Sets Provides a client-generated, opaque value with a 1 KB character limit that is recorded in the analytics logs when storage analytics logging is enabled..
     *
     * @param requestId the requestId value.
     * @return the service client itself
     */
    StorageClient withRequestId(String requestId);

    /**
     * Gets Gets or sets the preferred language for the response..
     *
     * @return the acceptLanguage value.
     */
    String acceptLanguage();

    /**
     * Sets Gets or sets the preferred language for the response..
     *
     * @param acceptLanguage the acceptLanguage value.
     * @return the service client itself
     */
    StorageClient withAcceptLanguage(String acceptLanguage);

    /**
     * Gets Gets or sets the retry timeout in seconds for Long Running Operations. Default value is 30..
     *
     * @return the longRunningOperationRetryTimeout value.
     */
    int longRunningOperationRetryTimeout();

    /**
     * Sets Gets or sets the retry timeout in seconds for Long Running Operations. Default value is 30..
     *
     * @param longRunningOperationRetryTimeout the longRunningOperationRetryTimeout value.
     * @return the service client itself
     */
    StorageClient withLongRunningOperationRetryTimeout(int longRunningOperationRetryTimeout);

    /**
     * Gets When set to true a unique x-ms-client-request-id value is generated and included in each request. Default is true..
     *
     * @return the generateClientRequestId value.
     */
    boolean generateClientRequestId();

    /**
     * Sets When set to true a unique x-ms-client-request-id value is generated and included in each request. Default is true..
     *
     * @param generateClientRequestId the generateClientRequestId value.
     * @return the service client itself
     */
    StorageClient withGenerateClientRequestId(boolean generateClientRequestId);

    /**
     * Gets the Services object to access its operations.
     * @return the Services object.
     */
    Services services();

    /**
     * Gets the Containers object to access its operations.
     * @return the Containers object.
     */
    Containers containers();

    /**
     * Gets the Blobs object to access its operations.
     * @return the Blobs object.
     */
    Blobs blobs();

    /**
     * Gets the BlockBlobs object to access its operations.
     * @return the BlockBlobs object.
     */
    BlockBlobs blockBlobs();

    /**
     * Gets the PageBlobs object to access its operations.
     * @return the PageBlobs object.
     */
    PageBlobs pageBlobs();

}
