/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.azure.storage.implementation;

import com.microsoft.azure.storage.AzureBlobStorage;
import com.microsoft.azure.storage.Services;
import com.microsoft.azure.storage.Containers;
import com.microsoft.azure.storage.Blobs;
import com.microsoft.azure.storage.BlockBlobs;
import com.microsoft.azure.storage.PageBlobs;
import com.microsoft.azure.storage.AppendBlobs;
import com.microsoft.rest.ServiceClient;
import com.microsoft.rest.RestClient;
import okhttp3.OkHttpClient;
import retrofit2.Retrofit;

/**
 * Initializes a new instance of the AzureBlobStorage class.
 */
public class AzureBlobStorageImpl extends ServiceClient implements AzureBlobStorage {

    /** The Azure storage account to use. */
    private String accountUrl;

    /**
     * Gets The Azure storage account to use.
     *
     * @return the accountUrl value.
     */
    public String accountUrl() {
        return this.accountUrl;
    }

    /**
     * Sets The Azure storage account to use.
     *
     * @param accountUrl the accountUrl value.
     * @return the service client itself
     */
    public AzureBlobStorageImpl withAccountUrl(String accountUrl) {
        this.accountUrl = accountUrl;
        return this;
    }

    /** Specifies the version of the operation to use for this request. */
    private String version;

    /**
     * Gets Specifies the version of the operation to use for this request.
     *
     * @return the version value.
     */
    public String version() {
        return this.version;
    }

    /**
     * Sets Specifies the version of the operation to use for this request.
     *
     * @param version the version value.
     * @return the service client itself
     */
    public AzureBlobStorageImpl withVersion(String version) {
        this.version = version;
        return this;
    }

    /**
     * The Services object to access its operations.
     */
    private Services services;

    /**
     * Gets the Services object to access its operations.
     * @return the Services object.
     */
    public Services services() {
        return this.services;
    }

    /**
     * The Containers object to access its operations.
     */
    private Containers containers;

    /**
     * Gets the Containers object to access its operations.
     * @return the Containers object.
     */
    public Containers containers() {
        return this.containers;
    }

    /**
     * The Blobs object to access its operations.
     */
    private Blobs blobs;

    /**
     * Gets the Blobs object to access its operations.
     * @return the Blobs object.
     */
    public Blobs blobs() {
        return this.blobs;
    }

    /**
     * The BlockBlobs object to access its operations.
     */
    private BlockBlobs blockBlobs;

    /**
     * Gets the BlockBlobs object to access its operations.
     * @return the BlockBlobs object.
     */
    public BlockBlobs blockBlobs() {
        return this.blockBlobs;
    }

    /**
     * The PageBlobs object to access its operations.
     */
    private PageBlobs pageBlobs;

    /**
     * Gets the PageBlobs object to access its operations.
     * @return the PageBlobs object.
     */
    public PageBlobs pageBlobs() {
        return this.pageBlobs;
    }

    /**
     * The AppendBlobs object to access its operations.
     */
    private AppendBlobs appendBlobs;

    /**
     * Gets the AppendBlobs object to access its operations.
     * @return the AppendBlobs object.
     */
    public AppendBlobs appendBlobs() {
        return this.appendBlobs;
    }

    /**
     * Initializes an instance of AzureBlobStorage client.
     */
    public AzureBlobStorageImpl() {
        this("https://{accountUrl}");
    }

    /**
     * Initializes an instance of AzureBlobStorage client.
     *
     * @param baseUrl the base URL of the host
     */
    private AzureBlobStorageImpl(String baseUrl) {
        super(baseUrl);
        initialize();
    }

    /**
     * Initializes an instance of AzureBlobStorage client.
     *
     * @param clientBuilder the builder for building an OkHttp client, bundled with user configurations
     * @param restBuilder the builder for building an Retrofit client, bundled with user configurations
     */
    public AzureBlobStorageImpl(OkHttpClient.Builder clientBuilder, Retrofit.Builder restBuilder) {
        this("https://{accountUrl}", clientBuilder, restBuilder);
        initialize();
    }

    /**
     * Initializes an instance of AzureBlobStorage client.
     *
     * @param baseUrl the base URL of the host
     * @param clientBuilder the builder for building an OkHttp client, bundled with user configurations
     * @param restBuilder the builder for building an Retrofit client, bundled with user configurations
     */
    private AzureBlobStorageImpl(String baseUrl, OkHttpClient.Builder clientBuilder, Retrofit.Builder restBuilder) {
        super(baseUrl, clientBuilder, restBuilder);
        initialize();
    }

    /**
     * Initializes an instance of AzureBlobStorage client.
     *
     * @param restClient the REST client containing pre-configured settings
     */
    public AzureBlobStorageImpl(RestClient restClient) {
        super(restClient);
        initialize();
    }

    private void initialize() {
        this.services = new ServicesImpl(retrofit(), this);
        this.containers = new ContainersImpl(retrofit(), this);
        this.blobs = new BlobsImpl(retrofit(), this);
        this.blockBlobs = new BlockBlobsImpl(retrofit(), this);
        this.pageBlobs = new PageBlobsImpl(retrofit(), this);
        this.appendBlobs = new AppendBlobsImpl(retrofit(), this);
    }
}
